fix: update node version in github workflow
The `npm test` command was failing in the GitHub Actions workflow due to an outdated Node.js version.
The error `TypeError: (0 , _os(...).availableParallelism) is not a function` indicates that the Node.js version being used did not support `os.availableParallelism()`.

This commit updates the Node.js version in the `.github/workflows/npm-publish.yml` file from `16.x` to `20.x` to resolve the issue.